#pragma once

#include <winioctl.h>

#define VIBEDECK_DEVICE_TYPE 0x8000

#define IOCTL_VIBEDECK_GET_STATUS CTL_CODE(VIBEDECK_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_VIBEDECK_ENABLE_DISPLAY CTL_CODE(VIBEDECK_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_VIBEDECK_DISABLE_DISPLAY CTL_CODE(VIBEDECK_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_VIBEDECK_SET_MODE CTL_CODE(VIBEDECK_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

typedef struct VIBEDECK_DISPLAY_MODE
{
    unsigned int Width;
    unsigned int Height;
    unsigned int RefreshRate;
} VIBEDECK_DISPLAY_MODE;

typedef struct VIBEDECK_DRIVER_STATUS
{
    unsigned int DriverVersion;
    unsigned int DisplayEnabled;
    unsigned int Width;
    unsigned int Height;
    unsigned int RefreshRate;
} VIBEDECK_DRIVER_STATUS;
